# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-15 21:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifycode',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='短信发送时间', verbose_name='添加时间'),
        ),
    ]
